#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 31 13:26:29 2023

@author: mndiaye
"""

#%%
"""
### Initialization
"""
import numpy as np
import slow_fourier_transform as sft
import disk_utils as du
import matplotlib.pyplot as plt
from astropy.io import fits
from pathlib import Path
# import pdb
import glob

import os

from mpl_toolkits.axes_grid1 import AxesGrid


import time

#%%
"""
### Parameters
"""
# Pupil size
nPup = 400

# Sampling of the coronagraph focal plane mask
nFPM = 100

# Image size
nImg = 400

# OPD map number in the files
nOPD = 2000

# wavelength in m

wl = 'H'

if wl == 'H' : 

    lam_0 = 1600e-9
    #liste de 11 wavelengths pour H band
    lam_list = [1.4e-6, 1.44e-6, 1.48e-6, 1.52e-6, 1.56e-6, 1.6e-6, 1.64e-6, 1.68e-6, 1.72e-6, 1.76e-6, 1.80e-6]

elif wl == 'J' :

    lam = 1200e-9
elif wl == 'Y': 
    
    lam = 1000e-9

# Pupil diameter in m 
D = 38.54


#%%
"""
### Working directory
"""
user = 'Adrien'
if user == 'Adrien':
    # File directory
    fdir_dat = Path('/home/asimonnin/Bureau/ThesisAdrien/Andes/Data_corono/data').resolve()
    # Directory for the OPD with the corresponding seed value
    fdir_res   = Path('/home/asimonnin/Bureau/ThesisAdrien/Andes/Data_corono/results/').resolve()
    # Directory for the OPD with the corresponding seed value
    fdir_plt   = Path('/home/asimonnin/Bureau/ThesisAdrien/Andes/Data_corono/plots/').resolve()

elif user == 'Mamadou':
    # File directory
    fdir_dat = Path('/Users/mndiaye/Library/CloudStorage/OneDrive-UniversitéNiceSophiaAntipolis/data/andes/data/').resolve()
    # Directory for the OPD with the corresponding seed value
    fdir_res   = Path('/Users/mndiaye/Library/CloudStorage/OneDrive-UniversitéNiceSophiaAntipolis/data/andes/results/').resolve()
    # Directory for the OPD with the corresponding seed value
    fdir_plt   = Path('/Users/mndiaye/Library/CloudStorage/OneDrive-UniversitéNiceSophiaAntipolis/data/andes/plots/').resolve()

# Directory for the pupils
fdir_pupil = fdir_dat / 'Pupil'
fdir_elt = '/home/asimonnin/Bureau/ThesisAdrien/Andes/Data_corono/data/elt/'

# Directory for the PSF generated by Anne-Laure Cheffaut
"""
Read OPDs
"""


fdir_opd = '/Users/asimonnin/Desktop/PhD/Andes/Data_corono/data/PASSATA/20240228_112033.0_Seeing_0_65' #median

# fdir_opd = '/Users/asimonnin/Desktop/PhD/Andes/Data_corono/data/PASSATA/20240228_053027.0_Seeing_0_57' #JQ2

fdir_opd = Path(fdir_opd).resolve()

# Filename and path for the OPD maps
flist_opd = os.listdir(fdir_opd) 
fpath_opd = [fdir_opd / flist_opd[i] for i in range(len(flist_opd)) if flist_opd[i].endswith('.fits')]
            
fpath_opd = sorted(fpath_opd)

fpath_opd = fpath_opd[200:2750]  #5min temps exposition
        
                
t0 = time.time()
# Read OPD maps for the nOPD files
OPD_arr = np.asarray([fits.getdata(fpath_opd[i]) for i in range(nOPD)])


# Filename and path for the ELT pupil
# fname_elt = 'Tel-Pupil.fits' Old pupil
fname_elt = 'ELT_pupil_400.fits' # new pupil
fpath_elt = fdir_pupil / fname_elt

#%%
"""
### Read file
"""
# Read ELT pupil 
# Pupil = fits.getdata(fpath_elt,)

Pupil = du.uniform_disk(nPup, nPup/2.)

    #%%
"""
### Coronagraphic components
"""
# Focal plane mask
mask2d = du.uniform_disk(nFPM, nFPM/2.)

#%%
for lam in lam_list :

    # conversion lradian to mas
    rad2mas = np.pi/(180.*3600*1000)
    mas2rad = 1/rad2mas

    # conversion lam/D to mas
    lamD2mas = (lam_0/D)*mas2rad

    # plate scale in mas per pixel
    pscale = 0.3

    # FPM size in lam/D in the focal plane B
    # mB = 4 

    # FoV in lam/D in the final image plane D
    mD = 58.393*(nImg/1600) * (lam_0/lam)
    # print(mD)

    """
    Pupil configuration
    """

    diam = 0.9
    obst = 0.4
    mB = 3.8 * lam_0/lam # mutiplier par lambda_0/lamdba # mB en fonction de lam or not ? 

    LyotStop2d = Pupil*(du.uniform_disk(nPup, diam*nPup/2)-du.uniform_disk(nPup, obst*nPup/2))

    #%%
    coro_config = 'lyot'

    
    Pupil_coro = Pupil  
 
    """
    ### Creating directories to save results for each configurations
    """
    
    resultat_no_coro_no_turb_rad = []
    resultat_no_coro_no_turb_int = []

    resultat_w_coro_no_turb_rad = []
    resultat_w_coro_no_turb_int = []

    resultat_no_coro_w_turb_rad = []
    resultat_no_coro_w_turb_int = []

    resultat_w_woro_w_turb_rad = []
    resultat_w_woro_w_turb_int = []

    """
    ### Compute perfect PSF
    """
    # Field in the entrance pupil plane A
    Fld_AA0 = Pupil_coro

    # Field in the entrance pupil plane C
    Fld_CC0 = Fld_AA0 * 1.*LyotStop2d

    # Field in the image plane D (no coronagraph)*
    Fld_DD0 = sft.sft(Fld_CC0, nImg, mD*diam) #diametre_lyot

    # Intensity 
    Int_DD0 = np.abs(Fld_DD0)**2

    # Normalized intensity
    norm_peakDD0 = 1/np.max(Int_DD0)
        
    Int_DD0 *= norm_peakDD0 #norm_peakDD0

    """
    ### Calcul of corono image without atmospheric turbulences
    """
        
    Fld_AA = Pupil_coro
    # focal plane B 
    Fld_BB = mask2d*sft.sft(Fld_AA, nFPM, mB)

    # pupil plane C before Lyot stop
    Fld_CC = Fld_AA - sft.isft(Fld_BB, nPup, mB)
    #definir font size
    plt.rcParams.update({'font.size': 20})            
   
    # pupil plane C after Lyot stop
    Fld_LL = Fld_CC*LyotStop2d
   
    # image plane D 
    Fld_DD = sft.sft(Fld_LL, nImg, mD*diam) #diametre_lyot

    # Intensity
    Int_DD = np.abs(Fld_DD)**2

    # Normalized intensity
    Int_DD *= norm_peakDD0 #norm_peakDD0

    Int_DD_prf_avg, rad_DD_prf_avg = du.profile(Int_DD, ptype='mean')
    Int_DD0_prf_avg, rad_DD0_prf_avg = du.profile(Int_DD0, ptype='mean')

    Int_DD0_prf_std, rad_DD0_prf_std = du.profile(Int_DD0, ptype='std')
    Int_DD_prf_std, rad_DD_prf_std = du.profile(Int_DD, ptype='std')

    rad_DD0_prf_avg_lamD = rad_DD0_prf_avg * mD/nImg
    rad_DD_prf_avg_lamD = rad_DD_prf_avg * mD/nImg

    rad_DD0_prf_avg_mas = rad_DD0_prf_avg_lamD * lamD2mas
    rad_DD_prf_avg_mas = rad_DD_prf_avg_lamD * lamD2mas

    resultat_w_coro_no_turb_rad.append(rad_DD_prf_avg)
    resultat_w_coro_no_turb_int.append(Int_DD_prf_avg)

    resultat_no_coro_no_turb_rad.append(rad_DD0_prf_avg)
    resultat_no_coro_no_turb_int.append(Int_DD0_prf_avg)

    """
    ### load OPD of Anne Laure
    """


    for i in range (nOPD):
        t1 = time.time()
        print(f'OPD reading file time: {t1-t0:.3f}s') 
    
    
        """
        ### Compute PSF (with errors)
        """


        t0 = time.time()
        Int_D0 = np.zeros((nImg, nImg))
        for iOPD in range(nOPD):
            # Field in the entrance pupil plane A
            Fld_A0 = Pupil_coro * np.exp(2*1j*np.pi*OPD_arr[iOPD]/lam) 
            # print(lam,lam_0)
            # Field in the entrance pupil plane C
            Fld_C0 = Fld_A0 * LyotStop2d
            # Field in the image plane D (no coronagraph)
            Fld_D0 = sft.sft(Fld_C0, nImg, mD*diam)#diametre_lyot mD*diam

            # Intensity 
            Int_D0 += np.abs(Fld_D0)**2

        t1 = time.time()       
        # print(f'PSF computation time: {t1-t0:.3f}s')  

        # Normalized intensity
        Int_D0 /= nOPD

    
        # Normalized intensity
        norm_peakD0 = 1/np.max(Int_D0)

        # norm_peak_2 = 1/np.max(Int_DD0)

        Int_D0 *= norm_peakD0

        """
        ### Compute coronographic image (with errors)
        """
        t0 = time.time()
        Int_D = np.zeros((nImg, nImg))
        for iOPD in range(nOPD):
            # pupil plane A
            Fld_A0 = Pupil_coro * np.exp(2*1j*np.pi*OPD_arr[iOPD]/lam)
        
            # focal plane B 
            Fld_B = mask2d*sft.sft(Fld_A0, nFPM, mB)
        
            # pupil plane C before Lyot stop
            Fld_C = Fld_A0 - sft.isft(Fld_B, nPup, mB)
            # pupil plane C after Lyot stop
            Fld_L = Fld_C*LyotStop2d
        
            # image plane D 
            Fld_D = sft.sft(Fld_L, nImg, mD*diam) #diametre_lyot *diam
        
            # Intensity
            Int_D += np.abs(Fld_D)**2    
        t1 = time.time()       
        # print(f'Coro image computation time: {t1-t0:.3f}s')  
    

        # Normalized intensity
        Int_D /= nOPD
    
        # Normalized intensity
        Int_D *= norm_peakD0#_no_lyot #* norm_peakD0
    

    
        """
        ### Compute the radial intensity profiles of the images
        """
        # computation of the averaged intensity profiles of the images   
        Int_D0_prf_avg, rad_D0_prf_avg = du.profile(Int_D0, ptype='mean')
        Int_D_prf_avg, rad_D_prf_avg = du.profile(Int_D, ptype='mean')


        # computation of the standard deviation intensity profiles of the images
        Int_D0_prf_std, rad_D0_prf_std = du.profile(Int_D0, ptype='std')
        Int_D_prf_std, rad_D_prf_std = du.profile(Int_D, ptype='std')



        # convert pixel scale into lam/D scale for the x-axis
        rad_D0_prf_avg_lamD = rad_D0_prf_avg * mD/nImg
        rad_D_prf_avg_lamD = rad_D_prf_avg * mD/nImg
        
        rad_D0_prf_avg_mas = rad_D0_prf_avg_lamD * lamD2mas
        rad_D_prf_avg_mas = rad_D_prf_avg_lamD * lamD2mas
        
        """
        ### Save images
        """
        resultat_no_coro_w_turb_rad.append(rad_D0_prf_avg_mas)
        resultat_no_coro_w_turb_int.append(Int_D0_prf_avg)

        resultat_w_woro_w_turb_rad.append(rad_D_prf_avg_mas)
        resultat_w_woro_w_turb_int.append(Int_D_prf_avg)



np.save(fdir_res / 'WL_diff_resultat_no_coro_no_turb_rad.npy', resultat_no_coro_no_turb_rad)
np.save(fdir_res / 'WL_diff_resultat_no_coro_no_turb_int.npy', resultat_no_coro_no_turb_int)

np.save(fdir_res / 'WL_diff_resultat_w_coro_no_turb_rad.npy', resultat_w_coro_no_turb_rad)
np.save(fdir_res / 'WL_diff_resultat_w_coro_no_turb_int.npy', resultat_w_coro_no_turb_int)

np.save(fdir_res / 'WL_diff_resultat_no_coro_w_turb_rad.npy', resultat_no_coro_w_turb_rad)
np.save(fdir_res / 'WL_diff_resultat_no_coro_w_turb_int.npy', resultat_no_coro_w_turb_int)

np.save(fdir_res / 'WL_diff_resultat_w_woro_w_turb_rad.npy', resultat_w_woro_w_turb_rad)
np.save(fdir_res / 'WL_diff_resultat_w_woro_w_turb_int.npy', resultat_w_woro_w_turb_int)


